### ISSUE TITLE
controllerListBegin() / End() example compile error

### ISSUE THREAD

**Issue by HomeSpan** [HomeSpan/HomeSpan#950]
### Discussed in https://github.com/HomeSpan/HomeSpan/discussions/947

<div type='discussions-op-text'>

<sup>Originally posted by **erickfr06** November 12, 2024</sup>
Hello

I can't compile the controllerListBegin() example from the API reference inside a HomeSpan sketch. 
The compiler error is "invalid use of incomplete type 'const class controller' as soon as iterator 'it' of the sample is present in code, except in the for() line. The loop for() at the start of the code is compiling and executing correctly, as far as 'it' is not present in the following code block : typically "it->isAdmin()" generate a compiler error.

Any help appreciated :-)

Bellow the API reference section with the sample code :

const_iterator controllerListBegin() and const_iterator controllerListEnd()
    returns a constant iterator pointing to either the beginning, or the end, of an opaque linked list that stores all controller data
    iterators should be defined using the auto keyword as follows: auto myIt=homeSpan.controllerListBegin();
    controller data can be read from a de-referenced iterator using the following methods:
        const uint8_t *getID() returns pointer to the 36-byte ID of the controller
        const uint8_t *getLTPK() returns pointer to the 32-byte Long Term Public Key of the controller
        boolean isAdmin() returns true if controller has admin permissions, else returns false
    click here for example code

    // Extract and print the same data about each controller that HomeSpan prints to the Serial Monitor when using the 's' CLI command

    Serial.printf("\nController Data\n");
    for(auto it=homeSpan.controllerListBegin(); it!=homeSpan.controllerListEnd(); ++it){  // loop over each controller
      Serial.printf("Admin=%d",it->isAdmin());    // indicate if controller has admin permissions
      Serial.printf("  ID=");                     // print the 36-byte Device ID of the controller
      for(int i=0;i<36;i++)
        Serial.printf("%02X",it->getID()[i]);
      Serial.printf("  LTPK=");                   // print the 32-byte Long-Term Public Key of the controller)
      for(int i=0;i<32;i++)
        Serial.printf("%02X",it->getLTPK()[i]);
      Serial.printf("\n");
    }</div>

**Comment by HomeSpan** [comment]
Confirmed bug --- will address in future update.

**Comment by HomeSpan** [comment]
This has been fixed.  Code available in dev branch for testing.

**Comment by erickfr06** [comment]
Thanks for your help. All seems to be OK now.
I've swapped code block into HS 1.9.1 library and the code compile perfectly now.
I still not use HS 2.x yet due to large binary code footprint while debuging with OTA active, even on minimum SPIFF (I always use these partition schema to have more space), on my poors legacy ESP32 devkits.

**Comment by HomeSpan** [comment]
Fix is now available in latest release v2.1.0.
